return {
	Sounds = {
		Pickup = { Id = "", Volume = 0.45, Pitch = 1, Spatial = true },
		Place = { Id = "", Volume = 0.5, PitchMin = 0.9, PitchMax = 1.3, Spatial = true },
		Coin = { Id = "", Volume = 0.25, MaxPerSecond = 6 },
		Full = { Id = "", Volume = 0.35 },
		RingComplete = { Id = "", Volume = 0.6 },
		Milestone = { Id = "", Volume = 0.5 },
		Countdown = { Id = "", Volume = 0.35 },
		LastPiece = { Id = "", Volume = 0.8 },
		EggGlow = { Id = "", Volume = 0.6 },
		EggCrack = { Id = "", Volume = 0.7 },
		EggBurst = { Id = "", Volume = 0.8 },
		Fanfare = { Id = "", Volume = 0.6 },
		Hatch = { Id = "", Volume = 0.6 },
		NextEgg = { Id = "", Volume = 0.5 },
		TrainStart = { Id = "", Volume = 0.4 },
		TrainLoop = { Id = "", Volume = 0.2, Looped = true },
		StatMilestone = { Id = "", Volume = 0.35 },
		GymUnlocked = { Id = "", Volume = 0.55 },
		Locked = { Id = "", Volume = 0.35 },
		Splash = { Id = "rbxasset://sounds/impact_water.mp3", Volume = 0.5 },
		RankUp = { Id = "", Volume = 0.55 },
		Purchase = { Id = "", Volume = 0.45 },
		Error = { Id = "", Volume = 0.35 },
		RobuxSuccess = { Id = "", Volume = 0.5 },
		ServerPack = { Id = "", Volume = 0.6 },
		Reward = { Id = "", Volume = 0.5 },
		Click = { Id = "", Volume = 0.35 },
		Open = { Id = "", Volume = 0.3 },
		Close = { Id = "", Volume = 0.3 },
		Ambience = { Id = "", Volume = 0.25, Looped = true },
		Music = { Id = "", Volume = 0.3, Looped = true },
		MusicFinal = { Id = "", Volume = 0.35, Looped = true },
	},
	Particles = {
		MaxPerBurst = 30,
		CullDistance = 150,
		LowQualityScale = 0.5,
	},
	CoinPopup = {
		PoolSize = 20,
		Rise = 3,
		Duration = 0.6,
	},
	Shake = {
		LastPiece = { Magnitude = 0.6, Duration = 0.4, Range = 300 },
		Burst = { Magnitude = 0.8, Duration = 0.45, Range = 400 },
	},
	Cutscene = {
		OrbitRadius = 230,
		OrbitHeight = 120,
		OrbitDegrees = 120,
		GlowTime = 2.5,
		CrackTime = 1.5,
		BurstTime = 1,
	},
	FinalMusicFraction = 0.9,
	CountdownFraction = 0.95,
	BandPulseSpeed = 2,
	TrailFirstTripOnly = true,
	MusicCrossfade = 2,
}
