return {
	Center = Vector3.new(0, 0, 0),
	Height = 160,
	MaxRadius = 55,
	WidestFraction = 0.42,
	ShellThickness = 3,
	GhostTransparency = 0.55,
	SegmentArcLength = 14,
	MinSegments = 6,
	BaseOffset = 12,

	ScaffoldWidth = 14,
	ScaffoldDirection = Vector3.new(0, 0, -1),
	ScaffoldMaxAngle = 45,
	ScaffoldGap = 5,
	ScaffoldShellClearance = 3,
	ScaffoldTopDistance = 8,
	ScaffoldStepRise = 1.6,
	ScaffoldPostEvery = 8,
	ScaffoldProfileStep = 0.5,

	BandHeightPadding = 1,
	BandVerticalReach = 9,
	BandHorizontalReach = 8,
	StandHeight = 3,

	NestInnerRadius = 50,
	NestOuterRadius = 66,
	NestHeight = 9,
}
