return {
	Center = Vector3.new(0, 0, 0),
	Height = 160,
	MaxRadius = 55,
	WidestFraction = 0.42,
	ShellThickness = 3,
	TileArc = 14,
	TileThickness = 0.3,
	TileSmoothing = 35,
	GhostTransparency = 0.55,
	SegmentArcLength = 9,
	MinSegments = 8,
	BaseOffset = 12,

	ScaffoldWidth = 16,
	ScaffoldDirection = Vector3.new(0, 0, -1),
	ScaffoldMaxAngle = 38,
	ScaffoldGap = 5,
	ScaffoldShellClearance = 3,
	ScaffoldTopDistance = 8,
	ScaffoldProfileStep = 0.5,
	ScaffoldThickness = 1.6,
	ScaffoldJointOverlap = 0.5,
	ScaffoldWallHeight = 1,
	ScaffoldWallWidth = 0.8,
	ScaffoldPillarEvery = 3,
	ScaffoldPillarSize = 2,
	ScaffoldPillarClearance = 6,
	ScaffoldSurfaceColor = Color3.fromRGB(232, 200, 140),
	ScaffoldWallColor = Color3.fromRGB(102, 64, 38),
	ScaffoldPillarColor = Color3.fromRGB(150, 98, 56),
	ScaffoldRevealTime = 0.45,
	RingShade = 0.07,

	BandHeightPadding = 1,
	BandVerticalReach = 9,
	BandHorizontalReach = 8,
	StandHeight = 3,
	PlaceZoneInset = 1.6,
	PlaceZoneThickness = 0.2,
	PlaceZoneLift = 0.06,
	PlacePromptDistance = 16,
	PlaceLabelHeight = 6,

	NestInnerRadius = 50,
	NestOuterRadius = 66,
	NestHeight = 9,
}
