return {
	Center = Vector3.new(0, 0, 0),
	Height = 160,
	MaxRadius = 55,
	WidestFraction = 0.42,
	ShellThickness = 3,
	GhostTransparency = 0.55,
	SegmentArcLength = 14,
	MinSegments = 6,
	BaseOffset = 12,

	ScaffoldWidth = 16,
	ScaffoldDirection = Vector3.new(0, 0, -1),
	ScaffoldMaxAngle = 52,
	ScaffoldGap = 5,
	ScaffoldShellClearance = 3,
	ScaffoldTopDistance = 8,
	ScaffoldProfileStep = 0.5,
	ScaffoldSegmentRise = 8,
	ScaffoldThickness = 2,
	ScaffoldJointOverlap = 0.6,
	ScaffoldWallHeight = 2.5,
	ScaffoldWallWidth = 1.5,
	ScaffoldPillarEvery = 2,
	ScaffoldPillarSize = 4,
	ScaffoldPillarClearance = 6,
	ScaffoldSurfaceColor = Color3.fromRGB(232, 200, 140),
	ScaffoldWallColor = Color3.fromRGB(150, 150, 160),
	ScaffoldPillarColor = Color3.fromRGB(115, 115, 128),

	BandHeightPadding = 1,
	BandVerticalReach = 9,
	BandHorizontalReach = 8,
	StandHeight = 3,

	NestInnerRadius = 50,
	NestOuterRadius = 66,
	NestHeight = 9,
}
