return {
	GameName = "Build an Egg!",
	GroupId = 433842257,
	DataStoreName = "BuildAnEgg_Player_v1",
	GlobalStoreName = "BuildAnEgg_Global_v1",
	SaveInStudio = false,
	AutosaveInterval = 120,
	SessionLockTimeout = 1800,
	ForeignLockWait = 10,
	ForeignLockRetryDelay = 2,
	DataLoadRetries = 6,
	DataRetryDelay = 1,

	CoinsPerPiece = 1,
	PickupHoldTime = 0,
	PlaceHoldTime = 0,
	PickupRepeat = 0.12,
	PlaceRepeat = 0.15,
	BasePromptDistance = 10,
	DistanceTolerance = 6,
	ActionCooldownFloor = 0.08,
	ActionCooldownSlack = 0.04,
	InteractRateLimit = 20,
	InteractRateWindow = 1,
	RequestRateLimit = 6,
	RequestRateWindow = 5,

	StateSyncInterval = 0.25,
	ServerProgressSyncInterval = 0.5,

	CompletionCutsceneTime = 6,
	InteriorDuration = 180,
	HatchAutoClaimDelay = 15,
	InteriorMinContribution = 1,
	Milestones = { 0.25, 0.5, 0.75, 0.9 },

	RingCount = 20,
	CarryVisualMax = 10,
	CarryBlockBaseSize = 2.2,
	CarryBlockGrowth = 0.55,
	CarryBlockMaxSize = 9,
	DropLifetime = 60,
	MaxDroppedPiles = 60,
	DropRateLimit = 3,
	FriendBoostPerFriend = 0.1,
	FriendBoostMax = 0.5,
	PurchaseTagTime = 3.5,
	CodeMaxLength = 32,
}
