return {
	GameName = "Build an Egg!",
	GroupId = 0,
	DataStoreName = "BuildAnEgg_Player_v1",
	GlobalStoreName = "BuildAnEgg_Global_v1",
	AutosaveInterval = 120,
	SessionLockTimeout = 1800,
	DataLoadRetries = 6,
	DataRetryDelay = 1,

	CoinsPerPiece = 1,
	PickupHoldTime = 0.6,
	PlaceHoldTime = 0.6,
	BasePromptDistance = 10,
	DistanceTolerance = 6,
	ActionCooldownFloor = 0.15,
	ActionCooldownSlack = 0.1,
	InteractRateLimit = 20,
	InteractRateWindow = 1,
	RequestRateLimit = 6,
	RequestRateWindow = 5,

	StateSyncInterval = 0.25,
	ServerProgressSyncInterval = 0.5,

	CompletionCutsceneTime = 6,
	InteriorDuration = 180,
	HatchAutoClaimDelay = 15,
	InteriorMinContribution = 1,
	Milestones = { 0.25, 0.5, 0.75, 0.9 },

	RingCount = 20,
	CarryVisualMax = 10,
	CodeMaxLength = 32,
}
