return {
	RemotesFolder = "Remotes",
	Remotes = {
		StateSync = "StateSync",
		ServerSync = "ServerSync",
		Notify = "Notify",
		Effect = "Effect",
		GymStop = "GymStop",
		Interact = "Interact",
		BuyUpgrade = "BuyUpgrade",
		ClaimGift = "ClaimGift",
		RedeemCode = "RedeemCode",
		ClaimHatch = "ClaimHatch",
	},
	RemoteKinds = {
		StateSync = "RemoteEvent",
		ServerSync = "RemoteEvent",
		Notify = "RemoteEvent",
		Effect = "UnreliableRemoteEvent",
		GymStop = "RemoteEvent",
		Interact = "RemoteEvent",
		BuyUpgrade = "RemoteFunction",
		ClaimGift = "RemoteFunction",
		RedeemCode = "RemoteFunction",
		ClaimHatch = "RemoteFunction",
	},
	World = {
		Root = "Game",
		Spawn = "Spawn",
		Quarry = "Quarry",
		QuarryZone = "QuarryZone",
		Pieces = "Pieces",
		PickupPrompt = "PickupPrompt",
		Site = "Site",
		Egg = "Egg",
		Rings = "Rings",
		Band = "Band",
		PlacePoints = "PlacePoints",
		PlacePrompt = "PlacePrompt",
		Scaffold = "Scaffold",
		Trail = "Trail",
		Gyms = "Gyms",
		Pad = "Pad",
		Interior = "Interior",
		Pool = "Pool",
		InteriorArrive = "Arrive",
		Gift = "FreeGift",
		GiftPrompt = "GiftPrompt",
		ShopStand = "ShopStand",
		UpgradeStand = "UpgradeStand",
		StandPrompt = "StandPrompt",
		EggBoard = "EggBoard",
	},
	Templates = {
		Folder = "Templates",
		RankTag = "RankTag",
		CarryStack = "CarryStack",
		GooseAura = "GooseAura",
		TrainAura = "TrainAura",
		CoinPopup = "CoinPopup",
	},
	Effects = {
		Folder = "Effects",
		Sounds = "Sounds",
		Particles = "Particles",
	},
	Gui = {
		Main = "Main",
	},
	Attributes = {
		Stat = "Stat",
		Tier = "Tier",
		Ring = "Ring",
		Segment = "Segment",
		GoldenGoose = "GoldenGoose",
		Training = "Training",
	},
}
