return {
	Rarities = {
		{ Key = "Common", Fragment = "Cracked", Color = Color3.fromRGB(205, 205, 212), Boost = 0.1, Height = 2.6, Weight = 70, Species = { "duck_pet", "bunny_pet", "hamster_pet", "pig_pet" } },
		{ Key = "Rare", Fragment = "Shiny", Color = Color3.fromRGB(80, 170, 255), Boost = 0.25, Height = 2.9, Weight = 22, Species = { "kitten_pet", "puppy_pet", "sheep_pet", "frog_pet" } },
		{ Key = "Epic", Fragment = "Glowing", Color = Color3.fromRGB(175, 95, 255), Boost = 0.5, Height = 3.2, Weight = 6, Species = { "fox_pet", "panda_pet", "penguin_pet", "raccoon_pet", "cow_pet" } },
		{ Key = "Legendary", Fragment = "Golden", Color = Color3.fromRGB(255, 190, 40), Boost = 1, Height = 3.5, Weight = 1.7, Species = { "owl_pet", "bear_cub_pet", "turtle_pet", "bee_pet", "axolotl_pet" } },
		{ Key = "Mythic", Fragment = "Prismatic", Color = Color3.fromRGB(255, 70, 130), Boost = 2.5, Height = 4, Weight = 0.3, Species = { "dragon_pet", "unicorn_pet" } },
	},
	Species = {
		duck_pet = { Name = "Duck" },
		bunny_pet = { Name = "Bunny" },
		hamster_pet = { Name = "Hamster" },
		pig_pet = { Name = "Pig" },
		kitten_pet = { Name = "Kitten" },
		puppy_pet = { Name = "Puppy" },
		sheep_pet = { Name = "Sheep" },
		frog_pet = { Name = "Frog" },
		fox_pet = { Name = "Fox" },
		panda_pet = { Name = "Panda" },
		penguin_pet = { Name = "Penguin" },
		raccoon_pet = { Name = "Raccoon" },
		cow_pet = { Name = "Cow" },
		owl_pet = { Name = "Owl", Flying = true },
		bear_cub_pet = { Name = "Bear Cub" },
		turtle_pet = { Name = "Turtle" },
		bee_pet = { Name = "Bee", Flying = true },
		axolotl_pet = { Name = "Axolotl" },
		dragon_pet = { Name = "Dragon", Flying = true },
		unicorn_pet = { Name = "Unicorn", Flying = true },
	},
	Pack = "PetPack",
	DarkThreshold = 0.2,
	Collections = {
		Common = { Index = 1, Name = "Meadow", Stat = "Strength", Color = Color3.fromRGB(240, 232, 214) },
		Silver = { Index = 2, Name = "Silver", Stat = "Speed", Color = Color3.fromRGB(200, 205, 215), Tint = { Color = Color3.fromRGB(205, 212, 226), Material = Enum.Material.Metal, Amount = 0.75 } },
		Golden = { Index = 3, Name = "Golden", Stat = "Strength", Color = Color3.fromRGB(255, 200, 60), Tint = { Color = Color3.fromRGB(255, 200, 50), Material = Enum.Material.Foil, Amount = 0.85 } },
		Void = { Index = 4, Name = "Void", Stat = "Speed", Color = Color3.fromRGB(120, 60, 180), Tint = { Color = Color3.fromRGB(95, 45, 150), Material = Enum.Material.SmoothPlastic, Amount = 0.8 }, Sparkle = Color3.fromRGB(220, 90, 255) },
		Gem = { Index = 5, Name = "Gem", Stat = "Both", Color = Color3.fromRGB(80, 230, 200), Tint = { Color = Color3.fromRGB(90, 235, 215), Material = Enum.Material.Glass, Amount = 0.75 }, Sparkle = Color3.fromRGB(120, 255, 240) },
		Lava = { Index = 6, Name = "Lava", Stat = "Strength", Color = Color3.fromRGB(255, 100, 40), Tint = { Color = Color3.fromRGB(255, 95, 35), Material = Enum.Material.SmoothPlastic, Amount = 0.85 }, Sparkle = Color3.fromRGB(255, 160, 60) },
		Frost = { Index = 7, Name = "Frost", Stat = "Speed", Color = Color3.fromRGB(170, 225, 255), Tint = { Color = Color3.fromRGB(175, 228, 255), Material = Enum.Material.Ice, Amount = 0.8 }, Sparkle = Color3.fromRGB(220, 245, 255) },
		Rainbow = { Index = 8, Name = "Rainbow", Stat = "Both", Color = Color3.fromRGB(255, 120, 200), Rainbow = true, Sparkle = Color3.fromRGB(255, 255, 255) },
	},
	FragmentsPerHatch = { Base = 3, PerLog = 1, Max = 8 },
	LuckPerLog = 0.6,
	Inputs = 5,
	MaxPets = 60,
	MaxFragments = 999,
	EquipSlots = 3,
	BothShare = 0.5,
	Follow = {
		Distance = 5,
		Spacing = 3.6,
		FlyHeight = 2.6,
		GroundOffset = -3,
		Lerp = 8,
		Bob = 0.35,
		BobSpeed = 4,
		CullDistance = 220,
	},
	Reveal = {
		ShakeTime = 1.6,
		ShakeAngle = 14,
		Spin = 40,
		Confetti = 40,
	},
	Messages = {
		Fragments = "+%d egg fragments!",
		PetsFull = "Pet inventory is full!",
		NeedFive = "Pick 5 items of the same tier",
		Hatched = "You got a %s %s!",
	},
}
