return {
	Directors = { 433636117 },
	LaunchData = "trailer",
	Attribute = "Trailer",
	AutoAttribute = "TrailerAuto",
	StartKey = Enum.KeyCode.T,
	AutoStart = 30,
	StartDelay = 1.5,
	Lead = 0.8,
	Tail = 0.6,
	FieldOfView = 70,
	FollowSharpness = 8,
	GrowStep = 0.1,
	CompleteDelay = 0.5,
	GameWait = 6,
	SyncFlash = { Time = 0.25, Color = Color3.new(1, 1, 1) },
	Setup = {
		Stats = { Coins = 1250000, Speed = 6, Strength = 250000, Eggs = 30 },
		TutorialDone = true,
		Upgrades = { BulkPickup = 6, BulkPlace = 6, Range = 2 },
		Pets = {
			{ Collection = "Divine", Rarity = 5 },
			{ Collection = "Galaxy", Rarity = 4 },
			{ Collection = "Rainbow", Rarity = 5 },
		},
		Progress = 0.55,
	},
	Shots = {
		{
			Name = "Hero",
			Time = 9,
			FieldOfView = 50,
			Stage = { Teleport = { Position = Vector3.new(0, 4, -300) } },
			Camera = { Mode = "Orbit", Center = Vector3.new(0, 70, 0), Radius = 250, RadiusTo = 225, Height = 25, HeightTo = 55, From = -125, To = -70, Focus = Vector3.new(0, 72, 0) },
		},
		{
			Name = "Quarry",
			Time = 7,
			FieldOfView = 55,
			Stage = { Teleport = { Position = Vector3.new(-32, -3, -192), Face = Vector3.new(1, 0, 0) }, Carry = 0, Loop = { Action = "Pickup", Every = 0.45 }, WalkSpeed = 12 },
			Move = { Vector3.new(30, -4, -196) },
			Camera = { Mode = "Follow", Offset = Vector3.new(-3, 5, -15), OffsetTo = Vector3.new(4, 4, -13), Look = Vector3.new(0, 3, 0) },
		},
		{
			Name = "Climb",
			Time = 8,
			FieldOfView = 55,
			Stage = { Teleport = { Scaffold = 30 }, Carry = 180, WalkSpeed = 16 },
			Move = { Scaffold = { From = 31, To = 72, Step = 3 } },
			Camera = { Mode = "Radial", Offset = Vector3.new(24, 9, -8), OffsetTo = Vector3.new(22, 7, 6), Look = Vector3.new(0, 3, 0) },
		},
		{
			Name = "Place",
			Time = 6,
			FieldOfView = 55,
			Stage = { Teleport = { Scaffold = "Band" }, Carry = 400, Loop = { Action = "Place", Every = 0.2 } },
			Camera = { Mode = "Radial", Offset = Vector3.new(16, 5, -12), OffsetTo = Vector3.new(15, 7, 10), Look = Vector3.new(-6, 4, 0) },
		},
		{
			Name = "Timelapse",
			Time = 8,
			FieldOfView = 50,
			Stage = { Teleport = { Position = Vector3.new(0, 4, -300) }, Carry = 0, Grow = { To = 0.97, Time = 7 } },
			Camera = { Mode = "Path", From = Vector3.new(175, 90, -175), To = Vector3.new(160, 100, -165), Focus = Vector3.new(0, 82, 0) },
		},
		{
			Name = "Flyover",
			Time = 9,
			FieldOfView = 60,
			Stage = {},
			Camera = { Mode = "Path", From = Vector3.new(-250, 40, -440), To = Vector3.new(60, 190, -380), Focus = Vector3.new(0, 80, -60), FocusTo = Vector3.new(0, 90, 0) },
		},
		{
			Name = "Treadmill",
			Time = 6,
			FieldOfView = 55,
			Stage = { Pad = { Tier = "Gym25", Stat = "Speed" } },
			Camera = { Mode = "Around", Radius = 13, RadiusTo = 11, Height = 3, HeightTo = 4, From = 50, To = 115, Look = Vector3.new(0, 1.5, 0) },
		},
		{
			Name = "Bench",
			Time = 6,
			FieldOfView = 55,
			Stage = { Pad = { Tier = "Gym25", Stat = "Strength" } },
			Camera = { Mode = "Around", Radius = 12, RadiusTo = 9, Height = 6, HeightTo = 4.5, From = -40, To = 20, Look = Vector3.new(0, 0, 0) },
		},
		{
			Name = "Pets",
			Time = 6,
			FieldOfView = 55,
			Stage = { Stop = true, Teleport = { Position = Vector3.new(-8, 4, -322), Face = Vector3.new(0, 0, 1) }, WalkSpeed = 11 },
			Move = { Vector3.new(-8, 3, -262) },
			Camera = { Mode = "Follow", Offset = Vector3.new(-7, 4, 14), OffsetTo = Vector3.new(-5, 3.5, 12), Look = Vector3.new(0, 1.5, 0) },
		},
		{
			Name = "Incubator",
			Time = 5,
			FieldOfView = 50,
			Stage = { Teleport = { Position = Vector3.new(65, 4, -206), Face = Vector3.new(1, 0, 0) } },
			Camera = { Mode = "Path", From = Vector3.new(73, 14, -215), To = Vector3.new(74, 12.5, -196), Focus = Vector3.new(88, 6.5, -205) },
		},
		{
			Name = "Goose",
			Time = 5,
			FieldOfView = 50,
			Stage = { Teleport = { Position = Vector3.new(48, 4, -262), Face = Vector3.new(1, 0, -1) } },
			Camera = { Mode = "Path", From = Vector3.new(50, 8, -287), To = Vector3.new(48, 9, -268), Focus = Vector3.new(62, 4.5, -275) },
		},
		{
			Name = "Hatch",
			Time = 30,
			Stage = { Teleport = { Scaffold = "Band" }, Carry = 0, Complete = true },
			Camera = { Mode = "Game" },
		},
	},
}
