return {
	Steps = {
		{ Key = "Quarry", Text = "Follow the green arrows to the SHELL QUARRY", Target = "World", World = "Quarry" },
		{ Key = "Pickup", Text = "Walk up to a shell and hold its prompt to pick it up", Target = "World", World = "Shell", MarkerHeight = 3.5 },
		{ Key = "Carry", Text = "Carry it to the green PLACE zone on the egg", Target = "World", World = "PlaceZone" },
		{ Key = "Place", Text = "Stand in the green zone and hold the Place prompt", Target = "World", World = "PlaceZone" },
		{ Key = "OpenUpgrades", Text = "Talk to the UPGRADES NPC", Target = "World", World = "UpgradesNPC" },
		{ Key = "BuyUpgrade", Text = "Buy Bulk Pickup - your first upgrade is FREE!", Target = "Gui", Gui = "UpgradeBuy", World = "UpgradesNPC", NeedsPanel = "Upgrades" },
		{ Key = "Gym", Text = "Step on a treadmill to train your Speed", Target = "World", World = "Gym" },
		{ Key = "OpenPets", Stage = "Pets", WaitFor = "Fragments", Text = "You got egg fragments! Open your PETS menu", Target = "Gui", Gui = "PetsButton" },
		{ Key = "OpenIncubator", Stage = "Pets", WaitFor = "Fragments", Text = "Open the INCUBATOR", Target = "Gui", Gui = "IncubatorButton", NeedsPanel = "Pets", OpenGui = { "PetsButton" } },
		{ Key = "AddFragments", Stage = "Pets", WaitFor = "Fragments", Text = "Press ADD until all 5 slots are filled", Target = "Gui", Gui = "IncubatorAdd", NeedsPanel = "Incubator", OpenGui = { "IncubatorButton", "PetsButton" } },
		{ Key = "HatchPet", Stage = "Pets", WaitFor = "Fragments", Text = "Press HATCH to merge them into a pet!", Target = "Gui", Gui = "IncubatorHatch", NeedsPanel = "Incubator", OpenGui = { "IncubatorButton", "PetsButton" } },
		{ Key = "EquipPet", Stage = "Pets", Text = "EQUIP your new pet to boost your stats!", Target = "Gui", Gui = "EquipButton", NeedsPanel = "Pets", OpenGui = { "PetsButton" } },
	},
	Interlude = {
		Steps = { Carry = true, Place = true },
		Label = "EGG HATCHING!",
		Outside = "The egg just hatched! Press GO INSIDE to train 2x until the next egg starts",
		Inside = "Swim in the golden pool to train 2x! The next egg starts soon",
	},
	BeamTexture = "rbxassetid://72139726825517",
	BeamColor = Color3.new(1, 1, 1),
	BeamWidth = 1.6,
	BeamTextureLength = 3,
	BeamTextureSpeed = 3,
	SpotlightTransparency = 0.3,
	SpotlightPadding = 0.012,
	SpotlightRing = true,
	SpotlightCorner = 14,
	SpotlightShade = 4000,
	SpotlightOutline = 4,
	SpotlightBlur = 14,
	SpotlightBlurMobile = 10,
	FingerSize = 0.15,
	FingerBob = 0.015,
	FingerSpeed = 5,
	MarkerHeight = 12,
	GuideNewPlayerPieces = 50,
}
