import type { Effort } from '../types'

export const CONFIG = {
  Usage: {
    BandEnabled: true,
    PaneOpenOnStart: false,
    RateWindowMs: 60 * 60 * 1000,
    MinSampleMs: 5 * 60 * 1000,
    HistoryMs: 6 * 60 * 60 * 1000,
    MaxSamples: 2000,
    TickMs: 30 * 1000,
    WarnAtPercent: 80,
    DangerAtPercent: 95,
    BarWidth: 20,
    Labels: {
      five_hour: '5h',
      seven_day: '7d',
      spend_limit: 'Spend',
    } as Record<string, string>,
  },

  Router: {
    EnabledByDefault: true,
    JudgeModel: 'sonnet',
    JudgeEffort: 'low' as Effort,
    JudgeTimeoutMs: 15000,
    JudgeMaxTokens: 200,
    MaxPromptChars: 6000,
    FollowUpMaxChars: 40,
    OverridePrefix: '~',
    Models: {
      haiku: 'claude-haiku-4-5-20251001',
      sonnet: 'claude-sonnet-5-5',
      opus: 'claude-opus-5-5',
    } as Record<string, string>,
    Efforts: ['low', 'medium', 'high', 'xhigh', 'max'] as Effort[],
    Fallback: { model: 'sonnet', effort: 'medium' as Effort },
    NoEffortModels: ['haiku'],
    Rubric: [
      'You route a coding task to the cheapest Claude model and effort that will still do it well.',
      'Models:',
      '- haiku: trivial edits, renames, formatting, short factual questions.',
      '- sonnet: most coding work, single-module features, clear bugs, explanations.',
      '- opus: multi-module architecture, subtle or unclear bugs, anti-exploit/security design, performance tuning, large refactors, vague requirements.',
      'Effort:',
      '- low: trivial. medium: routine. high: needs real reasoning. xhigh: hard multi-step. max: only the hardest problems.',
      'Reply with JSON only, no code fences: {"model":"haiku|sonnet|opus","effort":"low|medium|high|xhigh|max","reason":"max 12 words"}',
    ].join('\n'),
  },

  Pipeline: {
    Command: 'build',
    MaxRounds: 3,
    StageTimeoutMs: 20 * 60 * 1000,
    ReportDir: '.usage-router/reports',
    Writer: { Model: 'auto', Effort: 'auto' as Effort | 'auto' },
    Reviewer: { Model: 'opus', Effort: 'high' as Effort },
    Tester: { Model: 'sonnet', Effort: 'medium' as Effort },
    PassToken: 'VERDICT: PASS',
    FailToken: 'VERDICT: FAIL',
    WriterPrompt: [
      'You are a senior Roblox Luau engineer writing production code for Roblox Studio.',
      'Rules:',
      '- OOP with metatables, one ModuleScript per class, loaded through a module-loader pattern.',
      '- Every tunable value lives in a Config ModuleScript; extend existing configs instead of hardcoding.',
      '- Never create UI or RemoteEvents/RemoteFunctions with Instance.new; reference existing instances and list any the user must create, or give a Command Bar script that creates them.',
      '- Server authoritative: validate every remote argument (type, range, ownership, distance), rate-limit remotes, never trust the client.',
      '- Performance: task library only, no busy loops, disconnect connections, clean up instances, cache services and lookups, avoid per-frame allocation.',
      '- Use --!strict type annotations. No comments in code.',
      '- Do not invent Roblox APIs. If unsure an API exists, say so.',
      'Write the files to disk. End with a short list of files changed and any instances the user must create.',
    ].join('\n'),
    ReviewerPrompt: [
      'You review Roblox Luau code for exploits, lag and bugs. You do not edit files.',
      'Check: client-trusted values, unvalidated remote args, missing rate limits, sanity checks on position/distance/cooldowns, data loss in DataStore code (pcall, retries, session locking, BindToClose),',
      'memory leaks (connections, tables keyed by players not cleared on PlayerRemoving), heavy work in Heartbeat/RenderStepped, yields in wrong places, wait/spawn/delay instead of task.*, deprecated APIs, Instance.new used for UI or remotes, hardcoded values that belong in Config, comments in code.',
      'List each finding as: [severity: critical|major|minor] file:line - problem - exact fix.',
      'End with exactly one line: VERDICT: PASS (no critical or major findings) or VERDICT: FAIL.',
    ].join('\n'),
    TesterPrompt: [
      'You test Roblox Luau code outside Roblox Studio.',
      'Run whichever of these exist on PATH, on the changed files: luau-analyze, selene, stylua --check. Report exact output.',
      'Then trace the main code paths by reading the code: nil access, wrong types, infinite yields, race conditions on PlayerAdded/PlayerRemoving, edge cases (player leaves mid-action, spam firing remotes, zero/negative/NaN numbers).',
      'State clearly what you could not verify without running Studio.',
      'List failures as: file:line - problem - exact fix.',
      'End with exactly one line: VERDICT: PASS or VERDICT: FAIL.',
    ].join('\n'),
  },

  Pane: {
    Id: 'usage-router',
    Title: 'Usage Router',
    Command: 'control',
    RouteCommand: 'route',
  },
} as const
